name = "foxy-cloudflare-membership-site"
type = "javascript"
account_id = "CF_ACCOUNT_ID"
workers_dev = true
route = ""
zone_id = ""
vars = { FX_REDIRECT = "/dashboard" }

[env.development]
vars = { FX_REDIRECT = "/dashboard", FX_JWT_SECRET = "foobar"}

[env.production]
name = "foxy_customer_portal_authentication_guard"
vars = { FX_REDIRECT = "/dashboard" }
